# .github/workflows/llm-accessibility-fixer.yml
name: LLM + A11y MCP Accessibility Fixer

on:
  push:
    branches: [main, master]
    paths: 
      - '**.html'
      - '**.css'
  
  pull_request:
    branches: [main, master]
    paths:
      - '**.html'
      - '**.css'
  
  workflow_dispatch:
    inputs:
      force_fix:
        description: 'Force fixes even if no issues detected'
        required: false
        default: false
        type: boolean

jobs:
  fix-accessibility:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Create package.json
        run: |
          cat > package.json << 'EOF'
          {
            "name": "llm-a11y-fixer",
            "version": "1.0.0",
            "type": "module",
            "dependencies": {
              "@modelcontextprotocol/sdk": "^0.5.0",
              "openai": "^4.0.0"
            }
          }
          EOF

      - name: Install dependencies
        run: |
          npm install
          npm install -g a11y-mcp-server
          echo "✅ Dependencies installed"

      - name: Validate environment
        run: |
          if [ -z "${{ secrets.OPENAI_API_KEY }}" ]; then
            echo "❌ OPENAI_API_KEY secret is required"
            exit 1
          fi
          echo "✅ Environment validated"

      - name: Backup HTML files
        run: |
          echo "💾 Creating backups..."
          find . -name "*.html" -not -path "./.git/*" -not -path "./node_modules/*" | while read file; do
            cp "$file" "$file.original"
            echo "Backed up: $file"
          done

      - name: Run LLM accessibility fixer
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          echo "🤖 Starting LLM-powered accessibility fixes..."
          
          # Create scripts directory
          mkdir -p .github/scripts
          
          # Run the fixer script
          node .github/scripts/llm-accessibility-fixer.js

      - name: Check for changes
        id: changes
        run: |
          if git diff --quiet; then
            echo "changed=false" >> $GITHUB_OUTPUT
            echo "ℹ️ No changes detected"
          else
            echo "changed=true" >> $GITHUB_OUTPUT
            echo "✅ Changes detected"
            
            # Count changed files
            CHANGED_FILES=$(git diff --name-only | grep -c '\.html$' || echo "0")
            echo "html_files_changed=$CHANGED_FILES" >> $GITHUB_OUTPUT
            
            # Show what changed
            echo "Changed files:"
            git diff --name-only
          fi

      - name: Validate HTML after fixes
        if: steps.changes.outputs.changed == 'true'
        run: |
          echo "🔍 Validating HTML after fixes..."
          
          find . -name "*.html" -not -path "./.git/*" -not -path "./node_modules/*" | while read file; do
            echo "Checking: $file"
            
            # Basic validation - ensure file is valid HTML
            if ! grep -q "<!DOCTYPE" "$file"; then
              echo "⚠️ Warning: $file missing DOCTYPE"
            fi
            
            # Check for improvements
            ALT_COUNT=$(grep -c 'alt=' "$file" || echo "0")
            echo "✅ $file has $ALT_COUNT alt attributes"
          done

      - name: Commit changes
        if: steps.changes.outputs.changed == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "LLM Accessibility Bot"
          
          git add .
          
          git commit -m "🤖 Apply LLM-powered accessibility fixes

          - Fixed color contrast issues
          - Added missing alt text
          - Improved WCAG compliance
          - Files modified: ${{ steps.changes.outputs.html_files_changed }}
          
          Generated by: LLM + A11y MCP Server
          Trigger: ${{ github.event_name }}
          
          [accessibility] [automated]"
          
          git push

      - name: Create job summary
        if: always()
        run: |
          echo "## 🤖 LLM Accessibility Fixes" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Repository:** \`${{ github.repository }}\`" >> $GITHUB_STEP_SUMMARY
          echo "**Trigger:** ${{ github.event_name }}" >> $GITHUB_STEP_SUMMARY
          echo "**Time:** $(date -u '+%Y-%m-%d %H:%M:%S UTC')" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          
          if [ "${{ steps.changes.outputs.changed }}" == "true" ]; then
            echo "✅ **Status:** Accessibility fixes applied successfully" >> $GITHUB_STEP_SUMMARY
            echo "- HTML files modified: ${{ steps.changes.outputs.html_files_changed }}" >> $GITHUB_STEP_SUMMARY
            
            if [ -f ACCESSIBILITY_SUMMARY.md ]; then
              echo "" >> $GITHUB_STEP_SUMMARY
              echo "### 📊 Summary" >> $GITHUB_STEP_SUMMARY
              head -20 ACCESSIBILITY_SUMMARY.md >> $GITHUB_STEP_SUMMARY
            fi
          else
            echo "ℹ️ **Status:** No accessibility issues found - site is already accessible!" >> $GITHUB_STEP_SUMMARY
          fi
          
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "---" >> $GITHUB_STEP_SUMMARY
          echo "*Powered by LLM + [A11y MCP Server](https://github.com/ronantakizawa/a11ymcp)*" >> $GITHUB_STEP_SUMMARY

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: accessibility-reports-${{ github.run_number }}
          path: |
            ACCESSIBILITY_*.md
            *.html.original
          retention-days: 30